#!name=applemusic_list
#!homepage=https://github.com/mittw/shadowrocket-rules
#!desc=Rules:9 Created:07-29 12:46 Publisher:mittw
[Rule]
DOMAIN-SUFFIX,applemusic.com,PROXY
DOMAIN-SUFFIX,blobstore.apple.com,PROXY
DOMAIN-SUFFIX,music.apple.com,PROXY
DOMAIN,aod-ssl.itunes.apple.com,PROXY
DOMAIN,aod.itunes.apple.com,PROXY
DOMAIN,audio-ssl.itunes.apple.com,PROXY
DOMAIN,audio.itunes.apple.com,PROXY
DOMAIN,mvod.itunes.apple.com,PROXY
DOMAIN,streamingaudio.itunes.apple.com,PROXY
