#!name=onedrive_list
#!homepage=https://github.com/mittw/shadowrocket-rules
#!desc=Rules:13 Created:07-29 12:46 Publisher:mittw
[Rule]
DOMAIN-SUFFIX,1drv.com,PROXY
DOMAIN-SUFFIX,livefilestore.com,PROXY
DOMAIN-SUFFIX,microsoftpersonalcontent.com,PROXY
DOMAIN-SUFFIX,oneclient.sfx.ms,PROXY
DOMAIN-SUFFIX,onedrive.com,PROXY
DOMAIN-SUFFIX,onedrive.live.com,PROXY
DOMAIN-SUFFIX,photos.live.com,PROXY
DOMAIN-SUFFIX,sharepoint.com,PROXY
DOMAIN-SUFFIX,sharepointonline.com,PROXY
DOMAIN-SUFFIX,skydrive.wns.windows.com,PROXY
DOMAIN-SUFFIX,spoprod-a.akamaihd.net,PROXY
DOMAIN-SUFFIX,storage.live.com,PROXY
DOMAIN-SUFFIX,storage.msn.com,PROXY
